#!/bin/bash

## Send messages with Telegram form CLI.

defColors(){

	RC='\e[0m'	CYAN='\e[36m'	RED='\e[31m'	BOLD='\e[1m'	UL='\e[4m'
}

defColors

OPTION="${1}"
INPUT="${2}"
CHAT_ID="${3}"

TG_API_URL='https://api.telegram.org/bot'
TG_TOKEN_FILE="${HOME}/.config/telebash/telebash_token.txt"
TG_TOKEN=$( head -n 1 < "${TG_TOKEN_FILE}" )
FAV_FILE="${HOME}/.config/telebash/favorites.txt"


checkEnv(){

    REQUIREMENTS='curl'

    for R in ${REQUIREMENTS}; do

        if ! which "${R}">/dev/null;then

            echo -e "${RED}${R} not found!${BOLD}${RC}\n"
            exit 1

        fi

    done


    if [[ ! -f ${TG_TOKEN_FILE} || ! ${TG_TOKEN} ]];then

        echo -e "\n ${RED}Token is missing!\n ${RC}\n Get one with ${CYAN}@botfather${RC} on Telegram.\n"
        exit 1

    fi

}


helpMenu(){

    echo -e "\n\
  ${UL}Usage:${RC}\n\n\
    ./telebash <options> <input> <chat ID>\n\n\
    To get a chat ID, run this script with '--update'.\n\n\
  ${UL}Options:${RC}\n\n\
    -d, --document      <path>          Send a document.\n\
    -f, --favorites                     Show your favorites chat ID.
    -h, --help                          Display this help.\n\
    -t, --text          <text>          Send a text message.\n\
    -u, --update                        Get the latest infos (groups, messages...)\n"

}


showFavorites(){

    if [[ ! -f ${FAV_FILE} ]];then

        echo -e "${RED}Add favorites in ${FAV_FILE}${RC}"
        exit 1

    fi


    FAV_CHAT_ID="$( < "${FAV_FILE}" )"

    if [[ ! ${FAV_CHAT_ID} ]];then

        echo -e "${RED}Add favorites in ${FAV_FILE}${RC} (format: <chat id>@<username>)"
        exit 1

    fi


    for FAV in $( < "${FAV_FILE}" );do

        echo -e "\n${CYAN}\t ⭐ ${FAV}${RC}\n"

    done

}


ENDPOINTS=( sendMessage sendDocument getUpdates )


sendMessage(){

    ENDPOINT=${ENDPOINTS[0]}
    PARSE_MODE="markdown" ## Valid options are "html" or "markdown"

    curl\
        --silent "${TG_API_URL}${TG_TOKEN}/${ENDPOINT}"\
        --form chat_id="${CHAT_ID}"\
        --form parse_mode="${PARSE_MODE}"\
        --form text="${TEXT}"

}


sendDocument(){

    ENDPOINT=${ENDPOINTS[1]}

    curl\
        --silent "${TG_API_URL}${TG_TOKEN}/${ENDPOINT}"\
        --form document=@"${DOCUMENT}"\
        --form chat_id="${CHAT_ID}"
}

getUpdate(){

    ENDPOINT=${ENDPOINTS[2]}

    curl\
        --silent "${TG_API_URL}${TG_TOKEN}/${ENDPOINT}"

}


checkEnv


passFavID(){

    if [[ ! ${CHAT_ID} ]];then

	## Chat ID list in favorites must be <chat-id>@<alias>
		CHAT_ID=$( cut -d '@' -f 1 < "${FAV_FILE}" | head -n1)

		if [[ -z "${CHAT_ID}" ]]; then
            echo -e "${RED}Enter a chat ID! (No favorites found!)${RC}"
            exit 1
		fi

    fi

}


if [[ ! "${OPTION}" ]];then

    helpMenu
    exit 1

fi


case ${OPTION} in

    -d|--document)

        if [[ ! ${INPUT} ]];then

            echo -e "${RED}Enter the path to a document!${RC}"
            exit 1

        fi


        if [[ ! -e ${INPUT} ]];then

            echo -e "${RED}Can't find your document!${RC}"
            exit 1

        fi


		passFavID

        DOCUMENT=${INPUT}

        sendDocument

        ;;


    -f|--favorites)

        showFavorites

        ;;


    -h| --help)

        helpMenu

        ;;


    -t|--text)

        if [[ ! ${INPUT} ]];then

            echo -e "${RED}Enter a text!${RC}"
            exit 1

        fi


		passFavID

        TEXT=${INPUT}

        sendMessage

        ;;


    -u|--update)

        getUpdate

        ;;


    *)

        helpMenu

        ;;

esac
